### ISSUE TITLE
Error = Protocol._validateEnqueue        (However log_bin is definitely ON)

### ISSUE THREAD

**Issue by RobGordon406** [numtel/mysql-live-select#5]
Hi

If I run the SQL command: 
             SHOW VARIABLES LIKE 'log_bin';
Result is     
              log_bin = ON

But I get the following error message:
=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          
=> App running at: http://localhost:4000/

I20150322-14:18:05.092(10.5)? Exception from sub allPlayers id 3RGt6tzuECcPLizrQ Error: Cannot enqueue Query after fatal error.
I20150322-14:18:05.092(10.5)?     at Protocol._validateEnqueue (/Users/RobGordon/.meteor/packages/numtel_mysql/.0.1.4.nergik++os+web.browser+web.cordova/npm/node_modules/mysql/lib/protocol/Protocol.js:193:16)
I20150322-14:18:05.092(10.5)?     at Protocol._enqueue (/Users/RobGordon/.meteor/packages/numtel_mysql/.0.1.4.nergik++os+web.browser+web.cordova/npm/node_modules/mysql/lib/protocol/Protocol.js:129:13)
I20150322-14:18:05.092(10.5)?     at Connection.query (/Users/RobGordon/.meteor/packages/numtel_mysql/.0.1.4.nergik++os+web.browser+web.cordova/npm/node_modules/mysql/lib/Connection.js:185:25)
I20150322-14:18:05.093(10.5)?     at _update (/Users/RobGordon/.meteor/packages/numtel_mysql/.0.1.4.nergik++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/lib/LiveMysqlSelect.js:111:18)
I20150322-14:18:05.093(10.5)?     at LiveMysqlSelect.update (/Users/RobGordon/.meteor/packages/numtel_mysql/.0.1.4.nergik++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/lib/LiveMysqlSelect.js:124:5)
I20150322-14:18:05.093(10.5)?     at new LiveMysqlSelect (/Users/RobGordon/.meteor/packages/numtel_mysql/.0.1.4.nergik++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/lib/LiveMysqlSelect.js:27:10)
I20150322-14:18:05.093(10.5)?     at LiveMysql.select (/Users/RobGordon/.meteor/packages/numtel_mysql/.0.1.4.nergik++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/lib/LiveMysql.js:90:19)
I20150322-14:18:05.093(10.5)?     at [object Object]._handler (app/leaderboard.js:93:19)
I20150322-14:18:05.093(10.5)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150322-14:18:05.093(10.5)?     at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:950:1)

**Comment by glemiere** [comment]
In your mysql configuration file, just add : log-bin="the/folder/you/want/bin-log" for example.
In this case, you just configure mysql to save your binary logs in the folder you want, and name them with the prefix "bin-log".

For example on windows with xampp, edit my.ini to add the following line under [mysqld] : 
log-bin="C:/xampp/mysql/data/binlog/bin-log".

Don't forget to create folders if not already exists.

PS : I speaks about Windows because meteor.js is now available on windows, and maybe you want to test it ;)
